# Generated by Django 5.0.6 on 2024-06-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0002_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='lenght',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
