# Generated by Django 5.0.6 on 2024-06-17 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0003_word_lenght'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='lenght',
            new_name='length',
        ),
    ]
